In [44]:
import pandas as pd

data = {
    'Name': ['A', 'B', 'C', 'D'],
    'Age': [21, 22, 20, 23],
    'Marks': [85, 90, 78, 88]
}

df = pd.DataFrame(data)
df

  Name  Age  Marks
0    A   21     85
1    B   22     90
2    C   20     78
3    D   23     88

In [45]:
df.head()

  Name  Age  Marks
0    A   21     85
1    B   22     90
2    C   20     78
3    D   23     88

In [46]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      object
 1   Age     4 non-null      int64
 2   Marks   4 non-null      int64
dtypes: int64(2), object(1)
memory usage: 228.0+ bytes

In [47]:
df.describe()

             Age      Marks
count   4.000000   4.000000
mean   21.500000  85.250000
std     1.290994   5.251984
min    20.000000  78.000000
25%    20.750000  83.250000
50%    21.500000  86.500000
75%    22.250000  88.500000
max    23.000000  90.000000

In [48]:
df[df['Marks'] > 80]

  Name  Age  Marks
0    A   21     85
1    B   22     90
3    D   23     88

In [49]:
df['Grade'] = ['B', 'A', 'C', 'B']

In [50]:
df.sort_values(by='Marks', ascending=False)

  Name  Age  Marks Grade
1    B   22     90     A
3    D   23     88     B
0    A   21     85     B
2    C   20     78     C

In [51]:
df.groupby('Grade')['Marks'].mean()

Grade
A    90.0
B    86.5
C    78.0
Name: Marks, dtype: float64

In [52]:
df.isnull().sum()

Name     0
Age      0
Marks    0
Grade    0
dtype: int64

In [53]:
df.to_csv("student_data.csv", index=False)